/*
 * file name: system.c
 * 
 * system-level utilities:
 *   - SystemClock_Config
 *   - Delay              
 *   - Reset_All_State    
 *   - Stop_All_Timers    
 */

#include "stm32l4xx_hal.h"
#include "morse.h"

/*-----------------------------------
System_Clock_Config
generated by STM32CubeMX
----------------------------------- */
void System_Clock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
        while(1);

    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_MSI;
    RCC_OscInitStruct.MSIState            = RCC_MSI_ON;
    RCC_OscInitStruct.MSICalibrationValue = 0;
    RCC_OscInitStruct.MSIClockRange       = RCC_MSIRANGE_6;   /* 4 MHz */
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_NONE;

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
        while(1);

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_MSI;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
        while(1);
}


void Delay(uint32_t ms)
{
    for (uint32_t i = 0; i < ms; i++)
        for (volatile uint32_t j = 0; j < 680; j++);
}

// Stop_All_Timers --> immediately stops TIM2/3/6
void Stop_All_Timers(void)
{
    TIM2_Stop();
    TIM3_Stop();
    TIM6_Stop();
}

// Reset_All_State --> atomic cleanup called when mode is toggled
// stops all timers, clears all flags and buffers, hardware forced off
void Reset_All_State(void)
{
    // stop all timers 
    Stop_All_Timers();

    // clear all ISR-set flags
    g_flag_sw4_pressed        = 0;
    g_flag_sw4_released       = 0;
    g_flag_sw5_pressed        = 0;
    g_flag_tim6_fired         = 0;
    g_sw4_press_duration_ms   = 0;

    // reset encode state 
    g_enc_state       = ENC_IDLE;
    g_enc_pattern[0]  = '\0';
    g_enc_pattern_idx = 0;
    g_enc_symbol_ticks= 0;
    g_queue_head      = 0;
    g_queue_tail      = 0;
    g_tim2_ticks      = 0;

    // reset decode state
    g_dec_state    = DEC_IDLE;
    g_dec_buf_idx  = 0;
    g_dec_buf[0]   = '\0';

    // force buzzer and all LEDs off
    BUZZER_OFF();
    LED0_OFF();
    GPIOA->ODR &= ~(1U << 0);  
    GPIOC->ODR &= ~(1U << 7);  
    GPIOC->ODR &= ~(1U << 8); 

    // blank 7-segment
    Seg7_Clear();
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}


// Buzzer_Beep --> drives passive buzzer at ~500Hz for duration_ms milliseconds
void Buzzer_Beep(uint32_t duration_ms)
{
    for (uint32_t i = 0; i < duration_ms; i++)
    {
        BUZZER_TOG();
        Delay(1);
    }
    BUZZER_OFF();
}